## Cleaning

### Data Import

In [250]:
import polars as pl
import altair as alt
from dotenv import load_dotenv
import os

load_dotenv()  # automatically finds .env in current or parent directory

USER = os.getenv("USER")
PASSWORD = os.getenv("PW")
HOST = os.getenv("HOST")
DATABASE = os.getenv("DB_NAME")

uri = f"postgresql://{USER}:{PASSWORD}@{HOST}:5432/{DATABASE}"

query = "SELECT * FROM daan_822.article_detailed"

df = pl.read_database_uri(query=query, uri=uri)

In [251]:
df.describe()

shape: (9, 25)
┌───────────┬──────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ statistic ┆ pmid     ┆ doi       ┆ article_t ┆ … ┆ data_avai ┆ data_avai ┆ code_avai ┆ code_avai │
│ ---       ┆ ---      ┆ ---       ┆ ype       ┆   ┆ lable_det ┆ lable     ┆ lable_det ┆ lable     │
│ str       ┆ str      ┆ str       ┆ ---       ┆   ┆ ails      ┆ ---       ┆ ails      ┆ ---       │
│           ┆          ┆           ┆ str       ┆   ┆ ---       ┆ f64       ┆ ---       ┆ f64       │
│           ┆          ┆           ┆           ┆   ┆ str       ┆           ┆ str       ┆           │
╞═══════════╪══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ count     ┆ 7178     ┆ 7167      ┆ 7178      ┆ … ┆ 7178      ┆ 7178.0    ┆ 7178      ┆ 7178.0    │
│ null_coun ┆ 0        ┆ 11        ┆ 0         ┆ … ┆ 0         ┆ 0.0       ┆ 0         ┆ 0.0       │
│ t         ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ mean      ┆ null     ┆ null      ┆ null      ┆ … ┆ null      ┆ 0.395653  ┆ null      ┆ 0.033853  │
│ std       ┆ null     ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ min       ┆ 38168309 ┆ 10.1001/j ┆ abstract  ┆ … ┆ [" Data   ┆ 0.0       ┆ ["A       ┆ 0.0       │
│           ┆          ┆ amahealth ┆           ┆   ┆ are       ┆           ┆ GitHub    ┆           │
│           ┆          ┆ forum.202 ┆           ┆   ┆ available ┆           ┆ repositor ┆           │
│           ┆          ┆ 5.1…      ┆           ┆   ┆ on reque… ┆           ┆ y         ┆           │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆ containi… ┆           │
│ 25%       ┆ null     ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 50%       ┆ null     ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 75%       ┆ null     ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ max       ┆ 41716853 ┆ 10.9758/c ┆ systemati ┆ … ┆ []        ┆ 1.0       ┆ []        ┆ 1.0       │
│           ┆          ┆ pn.24.126 ┆ c-review  ┆   ┆           ┆           ┆           ┆           │
│           ┆          ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
└───────────┴──────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

### Cleaning

In [252]:
# labelling field names in the json construct for authors
dtypes = pl.List(
    pl.Struct(
        [
            pl.Field("given_names", pl.String),
            pl.Field("is_corresponding", pl.Boolean),
            pl.Field("orcid", pl.String),
            pl.Field("surname", pl.String),
        ]
    )
)

# add individual fileds for each in the authors json construct
df_parsed = (
    df.with_columns(
        pl.col("authors").str.json_decode(dtypes).alias("authors_struct"),
        pl.col("keywords").str.json_decode(pl.List(pl.String)).alias("keywords_list"),
    )
    .explode("authors_struct")
    .unnest("authors_struct")
    .with_columns(
        (pl.col("given_names") + " " + pl.col("surname")).alias("author_full_name")
    )
    .explode("keywords_list")
    .rename({"keywords_list": "keyword"})
    .drop(pl.col("authors"), pl.col("keywords"))
)

# identify columns that are json formatted in order to clean to be comma separated
json_array_cols = [
    col
    for col, dtype in df_parsed.schema.items()
    if dtype == pl.String
    and df_parsed.select(pl.col(col).drop_nulls().str.starts_with("[").all()).item()
]

# clean up commas in json columns and marking blank string as null. Converting string date to date type
df_final = (
    df_parsed.with_columns(
        [
            pl.col(col).str.json_decode(pl.List(pl.String)).list.join(", ").alias(col)
            for col in json_array_cols
        ]
    )
    .with_columns(pl.col("pub_date").str.strptime(pl.Date, "%Y-%m-%d", strict=False))
    .with_columns(pl.col(pl.String).str.strip_chars().replace("", None))
)

In [253]:
df_final.describe()

shape: (9, 29)
┌───────────┬──────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ statistic ┆ pmid     ┆ doi       ┆ article_t ┆ … ┆ orcid     ┆ surname   ┆ keyword   ┆ author_fu │
│ ---       ┆ ---      ┆ ---       ┆ ype       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ll_name   │
│ str       ┆ str      ┆ str       ┆ ---       ┆   ┆ str       ┆ str       ┆ str       ┆ ---       │
│           ┆          ┆           ┆ str       ┆   ┆           ┆           ┆           ┆ str       │
╞═══════════╪══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ count     ┆ 397097   ┆ 396732    ┆ 397097    ┆ … ┆ 104893    ┆ 395488    ┆ 375495    ┆ 395488    │
│ null_coun ┆ 0        ┆ 365       ┆ 0         ┆ … ┆ 292204    ┆ 1609      ┆ 21602     ┆ 1609      │
│ t         ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ mean      ┆ null     ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ std       ┆ null     ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ min       ┆ 38168309 ┆ 10.1001/j ┆ abstract  ┆ … ┆ http://or ┆ (AN)      ┆ (GLP1)    ┆ A Artiaga │
│           ┆          ┆ amahealth ┆           ┆   ┆ cid.org/0 ┆ Kimmings  ┆ receptor  ┆           │
│           ┆          ┆ forum.202 ┆           ┆   ┆ 000-0001- ┆           ┆ agonist   ┆           │
│           ┆          ┆ 5.1…      ┆           ┆   ┆ 500…      ┆           ┆           ┆           │
│ 25%       ┆ null     ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 50%       ┆ null     ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 75%       ┆ null     ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ max       ┆ 41716853 ┆ 10.9758/c ┆ systemati ┆ … ┆ https://o ┆ Țânțu     ┆ “new” ant ┆ “Andy” Ho │
│           ┆          ┆ pn.24.126 ┆ c-review  ┆   ┆ rcid.org/ ┆           ┆ ibiotics  ┆ Wing Chan │
│           ┆          ┆ 1         ┆           ┆   ┆ 0009-0009 ┆           ┆           ┆           │
│           ┆          ┆           ┆           ┆   ┆ -99…      ┆           ┆           ┆           │
└───────────┴──────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [254]:
cols_with_null_info = [
    (col, df_final.select(pl.col(f"{col}")).null_count().item(), df_final.schema[col])
    for col in df_final.columns
    if df_final.select(pl.col(col).null_count()).item() > 0
]

cols_with_null_info

[('doi', 365, String),
 ('article_subject', 1923, String),
 ('pub_date', 2074, Date),
 ('license_type', 397097, String),
 ('publisher_name', 33881, String),
 ('copyright_statement', 14594, String),
 ('copyright_year', 53928, String),
 ('abstract', 4926, String),
 ('affiliations', 6861, String),
 ('funding', 143571, String),
 ('data_available_details', 254375, String),
 ('code_available_details', 383523, String),
 ('given_names', 1690, String),
 ('is_corresponding', 18, Boolean),
 ('orcid', 292204, String),
 ('surname', 1609, String),
 ('keyword', 21602, String),
 ('author_full_name', 1609, String)]

## Analysis

In [255]:
df_final.schema

Schema([('pmid', String),
        ('doi', String),
        ('article_type', String),
        ('article_title', String),
        ('article_subject', String),
        ('pub_date', Date),
        ('reference_count', Int32),
        ('license_type', String),
        ('journal_title', String),
        ('publisher_name', String),
        ('copyright_statement', String),
        ('copyright_year', String),
        ('abstract', String),
        ('affiliations', String),
        ('has_supplemental', Boolean),
        ('figure_count', String),
        ('table_count', String),
        ('funding', String),
        ('data_available_details', String),
        ('data_available', Boolean),
        ('code_available_details', String),
        ('code_available', Boolean),
        ('given_names', String),
        ('is_corresponding', Boolean),
        ('orcid', String),
        ('surname', String),
        ('keyword', String),
        ('author_full_name', String)])

In [256]:
df.describe()

shape: (9, 25)
┌───────────┬──────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ statistic ┆ pmid     ┆ doi       ┆ article_t ┆ … ┆ data_avai ┆ data_avai ┆ code_avai ┆ code_avai │
│ ---       ┆ ---      ┆ ---       ┆ ype       ┆   ┆ lable_det ┆ lable     ┆ lable_det ┆ lable     │
│ str       ┆ str      ┆ str       ┆ ---       ┆   ┆ ails      ┆ ---       ┆ ails      ┆ ---       │
│           ┆          ┆           ┆ str       ┆   ┆ ---       ┆ f64       ┆ ---       ┆ f64       │
│           ┆          ┆           ┆           ┆   ┆ str       ┆           ┆ str       ┆           │
╞═══════════╪══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ count     ┆ 7178     ┆ 7167      ┆ 7178      ┆ … ┆ 7178      ┆ 7178.0    ┆ 7178      ┆ 7178.0    │
│ null_coun ┆ 0        ┆ 11        ┆ 0         ┆ … ┆ 0         ┆ 0.0       ┆ 0         ┆ 0.0       │
│ t         ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ mean      ┆ null     ┆ null      ┆ null      ┆ … ┆ null      ┆ 0.395653  ┆ null      ┆ 0.033853  │
│ std       ┆ null     ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ min       ┆ 38168309 ┆ 10.1001/j ┆ abstract  ┆ … ┆ [" Data   ┆ 0.0       ┆ ["A       ┆ 0.0       │
│           ┆          ┆ amahealth ┆           ┆   ┆ are       ┆           ┆ GitHub    ┆           │
│           ┆          ┆ forum.202 ┆           ┆   ┆ available ┆           ┆ repositor ┆           │
│           ┆          ┆ 5.1…      ┆           ┆   ┆ on reque… ┆           ┆ y         ┆           │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆ containi… ┆           │
│ 25%       ┆ null     ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 50%       ┆ null     ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 75%       ┆ null     ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ max       ┆ 41716853 ┆ 10.9758/c ┆ systemati ┆ … ┆ []        ┆ 1.0       ┆ []        ┆ 1.0       │
│           ┆          ┆ pn.24.126 ┆ c-review  ┆   ┆           ┆           ┆           ┆           │
│           ┆          ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
└───────────┴──────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [257]:
# creating a summary dataframe of common metrics
summary_df = pl.DataFrame(
    {
        "Metric": [
            "Total Articles",
            "Unique Authors",
            "Unique Keywords",
            "Avg Authors per Paper",
            "Avg Keywords per Paper",
        ],
        "Value": [
            df_final.n_unique("pmid"),
            df_final.n_unique("author_full_name"),
            df_final.n_unique("keyword"),
            df_final.group_by("pmid")
            .agg(pl.col("author_full_name").n_unique().alias("n_authors"))
            .select(pl.col("n_authors").mean().round(2))
            .item(),
            df_final.group_by("pmid")
            .agg(pl.col("keyword").n_unique().alias("n_keywords"))
            .select(pl.col("n_keywords").mean().round(2))
            .item(),
        ],
    },
    strict=False,
)

summary_df

shape: (5, 2)
┌────────────────────────┬─────────┐
│ Metric                 ┆ Value   │
│ ---                    ┆ ---     │
│ str                    ┆ f64     │
╞════════════════════════╪═════════╡
│ Total Articles         ┆ 7178.0  │
│ Unique Authors         ┆ 72963.0 │
│ Unique Keywords        ┆ 18719.0 │
│ Avg Authors per Paper  ┆ 11.47   │
│ Avg Keywords per Paper ┆ 5.0     │
└────────────────────────┴─────────┘

#### Building Visuals

In [258]:
data_avail = df_final.unique(subset=["pmid"]).group_by("data_available").agg(pl.len().alias("count"))

data_avail

shape: (2, 2)
┌────────────────┬───────┐
│ data_available ┆ count │
│ ---            ┆ ---   │
│ bool           ┆ u32   │
╞════════════════╪═══════╡
│ true           ┆ 2840  │
│ false          ┆ 4338  │
└────────────────┴───────┘

In [259]:
pub_year_counts = (
    df_final.with_columns(pl.col("pub_date").dt.year().alias("pub_year"))
    .group_by("pub_year")
    .agg(pl.col("pmid").n_unique().alias("num_articles"))
    .sort("pub_year")
)

pub_year_counts

shape: (4, 2)
┌──────────┬──────────────┐
│ pub_year ┆ num_articles │
│ ---      ┆ ---          │
│ i32      ┆ u32          │
╞══════════╪══════════════╡
│ null     ┆ 45           │
│ 2024     ┆ 90           │
│ 2025     ┆ 7036         │
│ 2026     ┆ 7            │
└──────────┴──────────────┘

In [260]:
pub_month_counts = (
    df_final
    .with_columns(
        pl.col("pub_date")
          .dt.truncate("1mo")
          .alias("pub_month")
    )
    .group_by("pub_month")
    .agg(pl.col("pmid").n_unique().alias("num_articles"))
    .sort("pub_month")
)

pub_month_counts

shape: (25, 2)
┌────────────┬──────────────┐
│ pub_month  ┆ num_articles │
│ ---        ┆ ---          │
│ date       ┆ u32          │
╞════════════╪══════════════╡
│ null       ┆ 45           │
│ 2024-03-01 ┆ 1            │
│ 2024-04-01 ┆ 1            │
│ 2024-05-01 ┆ 2            │
│ 2024-07-01 ┆ 7            │
│ …          ┆ …            │
│ 2025-11-01 ┆ 642          │
│ 2025-12-01 ┆ 563          │
│ 2026-01-01 ┆ 4            │
│ 2026-02-01 ┆ 1            │
│ 2026-05-01 ┆ 2            │
└────────────┴──────────────┘

In [261]:
top_keywords = (
    df_final
    .filter(pl.col("keyword").is_not_null())
    .group_by("keyword")
    .agg(pl.len().alias("count"))
    .sort("count", descending=True)
    .head(15)
)

top_keywords

shape: (15, 2)
┌───────────────────────────┬───────┐
│ keyword                   ┆ count │
│ ---                       ┆ ---   │
│ str                       ┆ u32   │
╞═══════════════════════════╪═══════╡
│ COVID-19                  ┆ 2148  │
│ artificial intelligence   ┆ 2114  │
│ machine learning          ┆ 2103  │
│ Machine learning          ┆ 1959  │
│ Epidemiology              ┆ 1444  │
│ …                         ┆ …     │
│ Artificial intelligence   ┆ 1264  │
│ Risk factors              ┆ 1233  │
│ electronic health records ┆ 1046  │
│ Long COVID                ┆ 1013  │
│ Cancer                    ┆ 1005  │
└───────────────────────────┴───────┘

In [262]:
top_authors = (
    df_final
    .filter(pl.col("author_full_name").is_not_null())
    .group_by("author_full_name")
    .agg(pl.len().alias("count"))
    .sort("count", descending=True)
    .head(15)
)

top_authors

shape: (15, 2)
┌──────────────────────┬───────┐
│ author_full_name     ┆ count │
│ ---                  ┆ ---   │
│ str                  ┆ u32   │
╞══════════════════════╪═══════╡
│ Kiyohide Fushimi     ┆ 205   │
│ Hideo Yasunaga       ┆ 110   │
│ Hiroki Matsui        ┆ 97    │
│ Jiang Bian           ┆ 92    │
│ Jing Wang            ┆ 75    │
│ …                    ┆ …     │
│ Gabor Erdoes         ┆ 62    │
│ Yang Liu             ┆ 62    │
│ Wei Wang             ┆ 60    │
│ Suchitra Rao         ┆ 60    │
│ Taynãna César Simões ┆ 60    │
└──────────────────────┴───────┘

#### Visualizing

In [268]:
(
    alt.Chart(data_avail)
    .mark_bar()
    .encode(
        x=alt.X("data_available:O", title=""),
        y=alt.Y("count:Q", title="Number of Articles"),
    )
    .properties(title="Data Availability")
)

alt.Chart(...)

In [264]:
(
    alt.Chart(pub_year_counts)
    .mark_bar()
    .encode(
        x=alt.X("pub_year:O", title="Publication Year"),
        y=alt.Y("num_articles:Q", title="Number of Articles"),
    )
    .properties(title="Publications per Year")
)

alt.Chart(...)

In [265]:
(
    alt.Chart(pub_month_counts)
    .mark_line(point=True)
    .encode(
        x=alt.X("pub_month:T", title="Publication Date"),
        y=alt.Y("num_articles:Q", title="Number of Articles")
    )
    .properties(title="Publications Over Time")
)

alt.Chart(...)

In [266]:
(
    alt.Chart(top_keywords)
    .mark_bar()
    .encode(
        x=alt.X(
            "keyword:O",
            title="Keyword",
            sort=alt.SortField("count", order="descending"),
        ),
        y=alt.Y("count:Q", title="Count"),
    )
    .properties(title="Top 15 Keywords")
)

alt.Chart(...)

In [267]:
(
    alt.Chart(top_authors)
    .mark_bar()
    .encode(
        x=alt.X(
            "author_full_name:O",
            title="Author",
            sort=alt.SortField("count", order="descending"),
        ),
        y=alt.Y("count:Q", title="Number of Articles"),
    )
    .properties(title="Top 15 Authors")
)

alt.Chart(...)